import { Product } from '../types';

export const initialProducts: Product[] = [
  {
    id: '1',
    nameAr: 'مجموعة العناية بالبشرة الفاخرة',
    nameEn: 'Luxury Skincare Set',
    descriptionAr: 'مجموعة متكاملة للعناية اليومية بالبشرة تحتوي على سيروم وكريم مرطب.',
    descriptionEn: 'Complete daily skincare set containing serum and moisturizer.',
    price: 450,
    oldPrice: 600,
    category: 'cosmetics',
    image: 'https://picsum.photos/400/400?random=1',
    isOffer: true,
  },
  {
    id: '2',
    nameAr: 'أحمر شفاه مات طويل الأمد',
    nameEn: 'Long-lasting Matte Lipstick',
    descriptionAr: 'أحمر شفاه عالي الجودة يدوم طويلاً بألوان جذابة.',
    descriptionEn: 'High quality long lasting lipstick in attractive colors.',
    price: 150,
    category: 'cosmetics',
    image: 'https://picsum.photos/400/400?random=2',
  },
  {
    id: '3',
    nameAr: 'ساعة ذكية رياضية',
    nameEn: 'Smart Sports Watch',
    descriptionAr: 'ساعة ذكية تدعم قياس نبضات القلب والخطوات.',
    descriptionEn: 'Smart watch supporting heart rate and steps tracking.',
    price: 850,
    category: 'electronics',
    image: 'https://picsum.photos/400/400?random=3',
  },
  {
    id: '4',
    nameAr: 'عطر الفراعنة الأصلي',
    nameEn: 'Original Pharaohs Perfume',
    descriptionAr: 'عطر برائحة شرقية مصرية أصيلة وجذابة.',
    descriptionEn: 'Perfume with an authentic and attractive Egyptian oriental scent.',
    price: 1200,
    oldPrice: 1500,
    category: 'cosmetics',
    image: 'https://picsum.photos/400/400?random=4',
    isOffer: true,
  },
  {
    id: '5',
    nameAr: 'سماعات بلوتوث عازلة للضوضاء',
    nameEn: 'Noise Cancelling Bluetooth Headphones',
    descriptionAr: 'سماعات عالية النقاء مع ميكروفون مدمج.',
    descriptionEn: 'High fidelity headphones with built-in microphone.',
    price: 550,
    category: 'electronics',
    image: 'https://picsum.photos/400/400?random=5',
  },
  {
    id: '6',
    nameAr: 'ماسكرة تكثيف الرموش',
    nameEn: 'Volumizing Mascara',
    descriptionAr: 'تعطي كثافة وطول للرموش بشكل طبيعي.',
    descriptionEn: 'Gives volume and length to eyelashes naturally.',
    price: 120,
    category: 'cosmetics',
    image: 'https://picsum.photos/400/400?random=6',
  }
];